services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: g-portal-app
    restart: unless-stopped
    volumes:
      - ${FILE_SERVER_PATH}/config/database.php:/var/www/html/config/database.php
      - ${FILE_SERVER_PATH}/uploads:/var/www/html/uploads
      - ${FILE_SERVER_PATH}/logs:/var/www/html/backend/logs
      - ${FILE_SERVER_PATH}/sessions:/var/www/html/sessions
    ports:
      - "${APP_HOST_PORT}:80"
    environment:
      - ${DB_TZ}
    depends_on:
      - db
    networks:
      - internal

  db:
    image: mariadb:10.4.32
    container_name: g-portal-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: g-portal
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: ${DB_TZ}
    ports:
      - "${DB_HOST_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
    name: webnet
    external: true
