# Put your required MariaDB or MySQL version here
FROM mariadb:12.3.2

# Add any additional MariaDB or MySQL configurations or dependencies you need here
COPY db/custom.cnf /etc/mysql/conf.d/custom.cnf

# COPY db/db.sql /docker-entrypoint-initdb.d/db.sql